### ISSUE TITLE
Render footer content and homepage (and elsewhere?)

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/elevator-ui#125]
Like this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/980170/236291119-d83252dd-2924-41f6-9169-72f6311c3628.png">

Questions:
- Which pages should have footers? (Or which shouldn't?)
- Are there cases when footer content shouldn't be visible on those pages?
- endpoint for getting content

**Comment by cmcfadden** [comment]
All pages should have a footer if it's been defined in the site. But we can also decide that a footer doesn't work within the current design - I don't think it's mission critical. Let's talk sometime
