### ISSUE TITLE
Add Drawers to Elevator

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/elevator-ui#133]
A drawer is a user-made group of assets.  The most common use case is faculty creating a drawer for specific assets to use with a specific lecture, like slides.

Not all users can create drawers, only users with specific permissions.

### Functionality

- [x] #164
- [x] #165
- [x] #166
- [x] #167
- [x] #168
- [x] #169
- [x] #170
- [ ] #171
- [x] #172

### Out of scope

- Users cannot update a drawer name once created. This functionality doesn't currently exist.
- creating an excerpt page
- sharing, i.e. editing permissions of the drawer.
- previous/next functionality like search results
- recent drawers

**Comment by cmcfadden** [comment]
Endpoints for drawers:

* List of all drawers user has: `/drawers/listDrawers/true`
* Contents of drawer: `/drawers/getDrawer/***$drawerId***`
* Remove item from drawer: `/drawers/removeFromDrawer/***$drawerId***/***$assetId***/true`
* Remove an excerpt from a drawer: `/drawers/removeExcerpt/***$drawerId***/***$excerptId***/true`
* Set sort order (sorting for drawer): `/drawers/setSortOrder/***$drawerId***/***$sortOrder***`
* Set custom sort order (manual dragging): `/drawers/setCustomOrder/***$drawerId***` (POST)

Custom sort ordering is probably a low priority, as that involves drag and drop and whatnot.
