### ISSUE TITLE
Delay loading iframe until page has loaded?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#18]

**Comment by jxjj** [comment]
Per conversation with James/Colin: 

This is an open question. Does this make the site feel more responsive?

By more responsive, we're looking at time to largest paint (we think?)

**Comment by jxjj** [comment]
The load feels pretty good to me now. What do you think @cmcfadden? This still need some work or are we good to close this?

**Comment by cmcfadden** [comment]
I think it's good
