### ISSUE TITLE
Remove from Drawer Confirm Modal renders tags in title

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#189]
<img width="559" alt="Screenshot 2023-07-06 at 6 37 52 AM" src="https://github.com/UMN-LATIS/elevator-ui/assets/211655/b8412368-3fc0-4ebf-8530-f3e1cc02323b">

**Comment by jxjj** [comment]
I mean, who puts html in their title?

**Comment by cmcfadden** [comment]
literally just this one record.

**Comment by jxjj** [comment]
... we could edit the record? 😉
