### ISSUE TITLE
rename Create Drawer button ?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#205]
Should it be "Create Drawer and Add Item"? (In the old UI, it just created the drawer but left the modal up, new UI actually adds the item and dismisses the modal)

**Comment by jxjj** [comment]
I thought about that and tried a few variations.

Here was the rationale:
- The longer button name made layout tricky and felt too long.
- I didn’t feel like more words on the button added clarity
- two clicks felt strange and confused me on the old site

In the end, context seemed enough to support a one click operation and shorter button names:

1. The modal is dismissed when clicked implying completion
2. The toast appearing confirms that it was added to the new drawer.

Whatever the case, the ui is changing to support excerpts. We can talk through adjustments in that PR.
