### ISSUE TITLE
Support pages with iframes

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#225]
Example here:
https://dev.elevator.umn.edu/defaultinstance/page/view/21

Has an <iframe> embed, but it doesn't render

**Comment by jxjj** [comment]
Interesting. I'm not seeing it in the server response either...

<img width="578" alt="ScreenShot 2023-08-28 at 14 03 53@2x" src="https://github.com/UMN-LATIS/elevator-ui/assets/980170/648f8c1e-616d-41a3-bed7-ccc43e562f86">

**Comment by jxjj** [comment]
nvm. It's there. just lost in ellipses....
