### ISSUE TITLE
Add map, timeline and gallery embedding

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#240]
(mirror existing site)

Embeds should track UI setting for site.

**Comment by jxjj** [comment]
For example, in the legacy ui:

1. Go to https://nibsda.elevator.umn.edu/search/s/ad41ae86-bf70-4453-b807-7a1a1278640c#map
2. Click Embed Map
3. Embed code shows in a modal:
```html
 <iframe width="640" height="480" src="//nibsda.elevator.umn.edu/search/map/ad41ae86-bf70-4453-b807-7a1a1278640c" frameborder="0" allowfullscreen></iframe>
 ```

None of this functionality exists yet in the new UI.
