### ISSUE TITLE
Wordpress plugin not working

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#256]
I can't recall if this worked at one point or not?

The Wordpress plugin works by spawning a window with the name 'elevatorPlugin'. When Elevator loads, it posts a `parentLoaded` message back to the opener, which responds with the rest of the Elevator plugin payload.

**Comment by jxjj** [comment]
It used to work, but I wouldn't be surprised if there's some regression.

Here's the og pr: https://github.com/UMN-LATIS/elevator-ui/pull/49

Anything in particular you're seeing (or not seeing)? This is what I'm seeing currently:

![ScreenShot 2023-11-21 at 16 07 33@2x](https://github.com/UMN-LATIS/elevator-ui/assets/980170/12913fde-3296-4db9-8707-a042fdebe9c6)

**Comment by cmcfadden** [comment]
Sorry I should have been more clear - it's the embedding side that isn't working. So clicking "browse assets" in WP spawns Elevator, but the icon never shows up to add the asset to Wordpress. 

Once items are embedded, they're just iframes basically, so that works.

**Comment by cmcfadden** [comment]
Confirmed this is still an issue
