### ISSUE TITLE
Cascade select in advanced search logging errors in console?

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#257]
Making a placeholder issue, noticed this while looking at something else.

![Screenshot 2024-01-04 at 1 15 45 PM](https://github.com/UMN-LATIS/elevator-ui/assets/211655/39c9e9d8-438b-4255-835c-9bc4d7e5d676)

**Comment by jxjj** [comment]
Do you recall more info about this? I'm not able to replicate with dev server – tried Safari and Chrome.

**Comment by cmcfadden** [comment]
hmm I can't seem to replicate issues either.

**Comment by jxjj** [comment]
line 141 has to do with initial value setting, so it's probably something specific returned from the server. We're doing some splitting on commas, so any field name with a comma might be sus.

I'll close for now, but reopen if you stumble on it again.
