### ISSUE TITLE
"Show More" appears even with content that hasn't been truncated

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/elevator-ui#27]
Example from https://dev.elevator.umn.edu/defaultinstance/asset/viewAsset/575ee4ceba98a87472f3e030

![Screenshot 2022-11-01 at 15 55 53@2x](https://user-images.githubusercontent.com/980170/199339335-ad44cf8b-c781-4ee2-87fb-68a36cc44ec3.png)

**Comment by cmcfadden** [comment]
Sorry, I duped this in #36 and fixed it (Issues weren't loading on the plane, didn't see this one)
