### ISSUE TITLE
Multiple entries for a given field aren't sorting properly

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/elevator-ui#35]
Items flagged "primary" should sort first

**Comment by cmcfadden** [comment]
Right now this is handled in widget_base.php:

```
public function primarySort() {
		foreach($this->fieldContentsArray as $key=>$fieldContents) {

			if($fieldContents->isPrimary) {
				unset($this->fieldContentsArray[$key]);
				array_unshift($this->fieldContentsArray, $fieldContents);
			}
		}
	}
```

That's called before rendering. We should decide where to best implement something similar. I think we could implement it `getWidgetContents` or in the `widgetContents` method in widget.vue.

**Comment by jxjj** [comment]
Example see: [Midnight in Paris asset notes](https://dev.elevator.umn.edu/defaultinstance//assetManager/editAsset/575ee4ceba98a87472f3e030) field. The primary note is below the other.

**Comment by cmcfadden** [comment]
One additional note - in general, the FieldContentsArray will be sorted in the way we want items displayed, as editors can drag and drop to rearrange them. Setting a primary item isn't mandatory. However, when they set a primary element, that *always* moves to the top, even if they hadn't explicitly dragged it to the top.

This is mostly an artifact of the fact that explicit sorting wasn't in the app originally and was added later.
