### ISSUE TITLE
Asset from Search Results should have Next and Previous navigation

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/elevator-ui#56]
Like this:

<img src="https://user-images.githubusercontent.com/980170/207101059-02061aca-c6f7-4fd8-9dcd-0edc809afc01.png" width="800" />

Chat with @cmcfadden about details

**Comment by cmcfadden** [comment]
- [ ] Update the endpoint to return JSON (@cmcfadden)
- [ ] Update the instance API to ensure we get the config data for "show next/prev" (@cmcfadden )

**Comment by cmcfadden** [comment]
Calling `/home/getInstanceNav` will now return `showPreviousNext` as part of the values, which tells us whether or not the next/previous results should display.

If a user visits an asset page by clicking a link from a search result, the links should show.

If a user clicks "next" or "previous", the app should query `/search/getResult/next/SEARCHID/ASSETID`. That will return a JSON payload like:
```
{
status: "found" / "notfound"
targetId: assetID?
}
```
