### ISSUE TITLE
Add ability for users to sort search results by a variety of properties

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/elevator-ui#57]
Like this:
![Screenshot 2022-12-12 at 10 36 38@2x](https://user-images.githubusercontent.com/980170/207101811-25992457-170c-412a-b9ca-0998417fa3b6.png)

**Comment by cmcfadden** [comment]
- [ ] @cmcfadden will add the sort data to the search results

**Comment by cmcfadden** [comment]
SearchResults endpoint now returns a `sortableWidgets` value which will be structured as key/value pair:

```
{ 
 0: "Best Match",
"lastModified.desc": "Modified Date (newest to oldest)",
"lastModified.asc": "Modified Date (oldest to newest)"
...
}
```

The sort array will be cached in redis, as it's kind of expensive (~160ms) to compute. (caching is disabled on dev)

**Comment by jxjj** [comment]
Resolved in https://github.com/UMN-LATIS/elevator-ui/pull/128
